// <auto-generated />
namespace MyAbpProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addpermissondefined : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpermissondefined));
        
        string IMigrationMetadata.Id
        {
            get { return "201803020545094_add-permissondefined"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
