// <auto-generated />
namespace MyAbpProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addrechargeentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrechargeentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060654370_add-recharge-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
